apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-deny
spec:
  description: "Default deny: Enforce strict namespace isolation"
  endpointSelector: {}
  ingress:
  - fromEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: "{{ .Namespace }}"
  egress:
  - toEndpoints:
      - matchLabels:
          io.kubernetes.pod.namespace: "{{ .Namespace }}"

