{{- range .Values.gateways }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .name }}-gateway
  namespace: {{ $.Values.defaultNamespace }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"  # GCP annotation for internal LB
spec:
  gatewayClassName: gke-l7
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: {{ .hostname }}
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .name }}-route
  namespace: {{ $.Values.defaultNamespace }}
spec:
  parentRefs:
  - name: {{ .name }}-gateway
  hostnames: ["{{ .hostname }}"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .serviceName }}
      port: 80
---
{{- end }}