gateways:
  - name: dcmg-cards
    hostname: dcmg-cards.example.com
    serviceName: bff-cards
  - name: dcmg-accounts
    hostname: dcmg-accounts.example.com
    serviceName: bff-accounts

services:
  - name: service-a
    versions:
      - v1
      - v2

defaultNamespace: default