apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: dcmg-accounts-gateway
  namespace: infra
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  gatewayClassName: gke-l7-rilb
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: accounts.dgcp.cloud
    allowedRoutes:
      namespaces:
        from: Same

        