apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: dcmg-cards-gateway
  namespace: infra
  annotations:
    networking.gke.io/load-balancer-type: "External"
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: cards.dgcp.cloud
    allowedRoutes:
      namespaces:
        from: Same